#ifndef GLOBALS_H
#define GLOBALS_H

#define MESSAGE_POLLING_TIMER_TICK 10*OS_TICK
#define MESSAGE_POLLING_BLOCK_SIZE 10

#define CLOCK_TICK 1000

enum {
   STOPWATCH_TASK,
   CLOCK_THREAD,
   CLOCK_AGENT,
   COUNTERS_THREAD,
   MINUTES_AGENT,
   SECONDS_AGENT
};

enum {
   STARTSTOP_BUTTON_PRESSED,
   RESET_BUTTON_PRESSED,
   STARTSTOP_CLOCK,
   RESET_COUNTER,
   SECONDS_TICK,
   MINUTES_TICK,
   DISPLAY_MINUTES,
   DISPLAY_SECONDS
};

#endif // GLOBALS_H
