//
// Created by Corrado Mio on 23/03/2024.
//

#include "cublas.h"

namespace cuda {

    std::map <cublasStatus_t, std::string> cublas_error::CUBLAS_ERRORS{
        {CUBLAS_STATUS_SUCCESS,          "success"},
        {CUBLAS_STATUS_NOT_INITIALIZED,  "not initialized"},
        {CUBLAS_STATUS_ALLOC_FAILED,     "alloc failed"},
        {CUBLAS_STATUS_INVALID_VALUE,    "invalid value"},
        {CUBLAS_STATUS_ARCH_MISMATCH,    "arch mismatch"},
        {CUBLAS_STATUS_MAPPING_ERROR,    "mapping error"},
        {CUBLAS_STATUS_EXECUTION_FAILED, "execution failed"},
        {CUBLAS_STATUS_INTERNAL_ERROR,   "internal error"},
        {CUBLAS_STATUS_NOT_SUPPORTED,    "not supported"},
        {CUBLAS_STATUS_LICENSE_ERROR,    "license error"},
        {cublasStatus_t(17),             "unknown error 17"},
        {cublasStatus_t(18),             "unknown error 18"},
        {cublasStatus_t(19),             "unknown error 19"},
        {cublasStatus_t(20),             "unknown error 20"}
    };

    // std::map <cudaError, std::string> cublas_error::CUDA_ERRORS{
    //     {cudaSuccess,                             "cudaSuccess"},
    //     {cudaErrorInvalidValue,                   "cudaErrorInvalidValue"},
    //     {cudaErrorMemoryAllocation,               "cudaErrorMemoryAllocation"},
    //     {cudaErrorInitializationError,            "cudaErrorInitializationError"},
    //     {cudaErrorCudartUnloading,                "cudaErrorCudartUnloading"},
    //     {cudaErrorProfilerDisabled,               "cudaErrorProfilerDisabled"},
    //     {cudaErrorProfilerNotInitialized,         "cudaErrorProfilerNotInitialized"},
    //     {cudaErrorProfilerAlreadyStarted,         "cudaErrorProfilerAlreadyStarted"},
    //     {cudaErrorProfilerAlreadyStopped,         "cudaErrorProfilerAlreadyStopped"},
    //     {cudaErrorInvalidConfiguration,           "cudaErrorInvalidConfiguration"},
    //     {cudaErrorInvalidPitchValue,              "cudaErrorInvalidPitchValue"},
    //     {cudaErrorInvalidSymbol,                  "cudaErrorInvalidSymbol"},
    //     {cudaErrorInvalidHostPointer,             "cudaErrorInvalidHostPointer"},
    //     {cudaErrorInvalidDevicePointer,           "cudaErrorInvalidDevicePointer"},
    //     {cudaErrorInvalidTexture,                 "cudaErrorInvalidTexture"},
    //     {cudaErrorInvalidTextureBinding,          "cudaErrorInvalidTextureBinding"},
    //     {cudaErrorInvalidChannelDescriptor,       "cudaErrorInvalidChannelDescriptor"},
    //     {cudaErrorInvalidMemcpyDirection,         "cudaErrorInvalidMemcpyDirection"},
    //     {cudaErrorAddressOfConstant,              "cudaErrorAddressOfConstant"},
    //     {cudaErrorTextureFetchFailed,             "cudaErrorTextureFetchFailed"},
    //     {cudaErrorTextureNotBound,                "cudaErrorTextureNotBound"},
    //     {cudaErrorSynchronizationError,           "cudaErrorSynchronizationError"},
    //     {cudaErrorInvalidFilterSetting,           "cudaErrorInvalidFilterSetting"},
    //     {cudaErrorInvalidNormSetting,             "cudaErrorInvalidNormSetting"},
    //     {cudaErrorMixedDeviceExecution,           "cudaErrorMixedDeviceExecution"},
    //     {cudaErrorNotYetImplemented,              "cudaErrorNotYetImplemented"},
    //     {cudaErrorMemoryValueTooLarge,            "cudaErrorMemoryValueTooLarge"},
    //     {cudaErrorStubLibrary,                    "cudaErrorStubLibrary"},
    //     {cudaErrorInsufficientDriver,             "cudaErrorInsufficientDriver"},
    //     {cudaErrorCallRequiresNewerDriver,        "cudaErrorCallRequiresNewerDriver"},
    //     {cudaErrorInvalidSurface,                 "cudaErrorInvalidSurface"},
    //     {cudaErrorDuplicateVariableName,          "cudaErrorDuplicateVariableName"},
    //     {cudaErrorDuplicateTextureName,           "cudaErrorDuplicateTextureName"},
    //     {cudaErrorDuplicateSurfaceName,           "cudaErrorDuplicateSurfaceName"},
    //     {cudaErrorDevicesUnavailable,             "cudaErrorDevicesUnavailable"},
    //     {cudaErrorIncompatibleDriverContext,      "cudaErrorIncompatibleDriverContext"},
    //     {cudaErrorMissingConfiguration,           "cudaErrorMissingConfiguration"},
    //     {cudaErrorPriorLaunchFailure,             "cudaErrorPriorLaunchFailure"},
    //     {cudaErrorLaunchMaxDepthExceeded,         "cudaErrorLaunchMaxDepthExceeded"},
    //     {cudaErrorLaunchFileScopedTex,            "cudaErrorLaunchFileScopedTex"},
    //     {cudaErrorLaunchFileScopedSurf,           "cudaErrorLaunchFileScopedSurf"},
    //     {cudaErrorSyncDepthExceeded,              "cudaErrorSyncDepthExceeded"},
    //     {cudaErrorLaunchPendingCountExceeded,     "cudaErrorLaunchPendingCountExceeded"},
    //     {cudaErrorInvalidDeviceFunction,          "cudaErrorInvalidDeviceFunction"},
    //     {cudaErrorNoDevice,                       "cudaErrorNoDevice"},
    //     {cudaErrorInvalidDevice,                  "cudaErrorInvalidDevice"},
    //     {cudaErrorDeviceNotLicensed,              "cudaErrorDeviceNotLicensed"},
    //     {cudaErrorSoftwareValidityNotEstablished, "cudaErrorSoftwareValidityNotEstablished"},
    //     {cudaErrorStartupFailure,                 "cudaErrorStartupFailure"},
    //     {cudaErrorInvalidKernelImage,             "cudaErrorInvalidKernelImage"},
    //     {cudaErrorDeviceUninitialized,            "cudaErrorDeviceUninitialized"},
    //     {cudaErrorMapBufferObjectFailed,          "cudaErrorMapBufferObjectFailed"},
    //     {cudaErrorUnmapBufferObjectFailed,        "cudaErrorUnmapBufferObjectFailed"},
    //     {cudaErrorArrayIsMapped,                  "cudaErrorArrayIsMapped"},
    //     {cudaErrorAlreadyMapped,                  "cudaErrorAlreadyMapped"},
    //     {cudaErrorNoKernelImageForDevice,         "cudaErrorNoKernelImageForDevice"},
    //     {cudaErrorAlreadyAcquired,                "cudaErrorAlreadyAcquired"},
    //     {cudaErrorNotMapped,                      "cudaErrorNotMapped"},
    //     {cudaErrorNotMappedAsArray,               "cudaErrorNotMappedAsArray"},
    //     {cudaErrorNotMappedAsPointer,             "cudaErrorNotMappedAsPointer"},
    //     {cudaErrorECCUncorrectable,               "cudaErrorECCUncorrectable"},
    //     {cudaErrorUnsupportedLimit,               "cudaErrorUnsupportedLimit"},
    //     {cudaErrorDeviceAlreadyInUse,             "cudaErrorDeviceAlreadyInUse"},
    //     {cudaErrorPeerAccessUnsupported,          "cudaErrorPeerAccessUnsupported"},
    //     {cudaErrorInvalidPtx,                     "cudaErrorInvalidPtx"},
    //     {cudaErrorInvalidGraphicsContext,         "cudaErrorInvalidGraphicsContext"},
    //     {cudaErrorNvlinkUncorrectable,            "cudaErrorNvlinkUncorrectable"},
    //     {cudaErrorJitCompilerNotFound,            "cudaErrorJitCompilerNotFound"},
    //     {cudaErrorUnsupportedPtxVersion,          "cudaErrorUnsupportedPtxVersion"},
    //     {cudaErrorJitCompilationDisabled,         "cudaErrorJitCompilationDisabled"},
    //     {cudaErrorUnsupportedExecAffinity,        "cudaErrorUnsupportedExecAffinity"},
    //     {cudaErrorUnsupportedDevSideSync,         "cudaErrorUnsupportedDevSideSync"},
    //     {cudaErrorInvalidSource,                  "cudaErrorInvalidSource"},
    //     {cudaErrorFileNotFound,                   "cudaErrorFileNotFound"},
    //     {cudaErrorSharedObjectSymbolNotFound,     "cudaErrorSharedObjectSymbolNotFound"},
    //     {cudaErrorSharedObjectInitFailed,         "cudaErrorSharedObjectInitFailed"},
    //     {cudaErrorOperatingSystem,                "cudaErrorOperatingSystem"},
    //     {cudaErrorInvalidResourceHandle,          "cudaErrorInvalidResourceHandle"},
    //     {cudaErrorIllegalState,                   "cudaErrorIllegalState"},
    //     {cudaErrorSymbolNotFound,                 "cudaErrorSymbolNotFound"},
    //     {cudaErrorNotReady,                       "cudaErrorNotReady"},
    //     {cudaErrorIllegalAddress,                 "cudaErrorIllegalAddress"},
    //     {cudaErrorLaunchOutOfResources,           "cudaErrorLaunchOutOfResources"},
    //     {cudaErrorLaunchTimeout,                  "cudaErrorLaunchTimeout"},
    //     {cudaErrorLaunchIncompatibleTexturing,    "cudaErrorLaunchIncompatibleTexturing"},
    //     {cudaErrorPeerAccessAlreadyEnabled,       "cudaErrorPeerAccessAlreadyEnabled"},
    //     {cudaErrorPeerAccessNotEnabled,           "cudaErrorPeerAccessNotEnabled"},
    //     {cudaErrorSetOnActiveProcess,             "cudaErrorSetOnActiveProcess"},
    //     {cudaErrorContextIsDestroyed,             "cudaErrorContextIsDestroyed"},
    //     {cudaErrorAssert,                         "cudaErrorAssert"},
    //     {cudaErrorTooManyPeers,                   "cudaErrorTooManyPeers"},
    //     {cudaErrorHostMemoryAlreadyRegistered,    "cudaErrorHostMemoryAlreadyRegistered"},
    //     {cudaErrorHostMemoryNotRegistered,        "cudaErrorHostMemoryNotRegistered"},
    //     {cudaErrorHardwareStackError,             "cudaErrorHardwareStackError"},
    //     {cudaErrorIllegalInstruction,             "cudaErrorIllegalInstruction"},
    //     {cudaErrorMisalignedAddress,              "cudaErrorMisalignedAddress"},
    //     {cudaErrorInvalidAddressSpace,            "cudaErrorInvalidAddressSpace"},
    //     {cudaErrorInvalidPc,                      "cudaErrorInvalidPc"},
    //     {cudaErrorLaunchFailure,                  "cudaErrorLaunchFailure"},
    //     {cudaErrorCooperativeLaunchTooLarge,      "cudaErrorCooperativeLaunchTooLarge"},
    //     {cudaErrorNotPermitted,                   "cudaErrorNotPermitted"},
    //     {cudaErrorNotSupported,                   "cudaErrorNotSupported"},
    //     {cudaErrorSystemNotReady,                 "cudaErrorSystemNotReady"},
    //     {cudaErrorSystemDriverMismatch,           "cudaErrorSystemDriverMismatch"},
    //     {cudaErrorCompatNotSupportedOnDevice,     "cudaErrorCompatNotSupportedOnDevice"},
    //     {cudaErrorMpsConnectionFailed,            "cudaErrorMpsConnectionFailed"},
    //     {cudaErrorMpsRpcFailure,                  "cudaErrorMpsRpcFailure"},
    //     {cudaErrorMpsServerNotReady,              "cudaErrorMpsServerNotReady"},
    //     {cudaErrorMpsMaxClientsReached,           "cudaErrorMpsMaxClientsReached"},
    //     {cudaErrorMpsMaxConnectionsReached,       "cudaErrorMpsMaxConnectionsReached"},
    //     {cudaErrorMpsClientTerminated,            "cudaErrorMpsClientTerminated"},
    //     {cudaErrorCdpNotSupported,                "cudaErrorCdpNotSupported"},
    //     {cudaErrorCdpVersionMismatch,             "cudaErrorCdpVersionMismatch"},
    //     {cudaErrorStreamCaptureUnsupported,       "cudaErrorStreamCaptureUnsupported"},
    //     {cudaErrorStreamCaptureInvalidated,       "cudaErrorStreamCaptureInvalidated"},
    //     {cudaErrorStreamCaptureMerge,             "cudaErrorStreamCaptureMerge"},
    //     {cudaErrorStreamCaptureUnmatched,         "cudaErrorStreamCaptureUnmatched"},
    //     {cudaErrorStreamCaptureUnjoined,          "cudaErrorStreamCaptureUnjoined"},
    //     {cudaErrorStreamCaptureIsolation,         "cudaErrorStreamCaptureIsolation"},
    //     {cudaErrorStreamCaptureImplicit,          "cudaErrorStreamCaptureImplicit"},
    //     {cudaErrorCapturedEvent,                  "cudaErrorCapturedEvent"},
    //     {cudaErrorStreamCaptureWrongThread,       "cudaErrorStreamCaptureWrongThread"},
    //     {cudaErrorTimeout,                        "cudaErrorTimeout"},
    //     {cudaErrorGraphExecUpdateFailure,         "cudaErrorGraphExecUpdateFailure"},
    //     {cudaErrorExternalDevice,                 "cudaErrorExternalDevice"},
    //     {cudaErrorInvalidClusterSize,             "cudaErrorInvalidClusterSize"},
    //     {cudaErrorUnknown,                        "cudaErrorUnknown"},
    //     {cudaErrorApiFailureBase,                 "cudaErrorApiFailureBase"}
    // };

}
